# Generated by Django 3.1.7 on 2021-03-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaatripackages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='package_images'),
        ),
        migrations.AddField(
            model_name='package',
            name='pricing',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='content',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=255)),
                ('package', models.ManyToManyField(to='yaatripackages.Package')),
            ],
        ),
    ]
